name: Test on Push and Pull Request

on:
  push:
    branches: ["*"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE.txt"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE.txt"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

