name: Test on Push and Pull Request

on:
  push:
    branches: ["*"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE.txt"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE.txt"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

